### ISSUE TITLE
Promise rejections for TCP errors aren't returned to the user

### ISSUE THREAD

**Issue by spiffytech** [ryclarke/cisco-kube-client#1]
Replication: attempt to retrieve a resource using auth credentials and an HTTP endpoint (not HTTPS).

Error message: 

```
[2016-06-23T20:15:28.841Z] FATAL: cisco-kube-client/20490 on spiffywork: socket hang up (endpoint=api/v1/namespaces, err.code=ECONNRESET)
    Error: socket hang up
        at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
        at TLSSocket.g (events.js:286:16)
        at emitNone (events.js:91:20)
        at TLSSocket.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:926:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-06-23T20:15:28.842Z]  WARN: cacher/express/20490 on spiffywork:
    Possibly Unhandled Rejection at: Promise [object Promise] reason: Error: socket hang up
        at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
        at TLSSocket.g (events.js:286:16)
        at emitNone (events.js:91:20)
        at TLSSocket.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:926:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ryclarke** [comment]
Same underlying problem as https://github.com/ryclarke/cisco-kube-client/issues/2, so I am closing this to consolidate them.
